[profile.default]
src = "src"
out = "out"
solc = "0.8.19"
libs = ["lib"]
remappings = [
    '@superfluid-finance/ethereum-contracts/=lib/superfluid-protocol-monorepo/packages/ethereum-contracts',
    '@superfluid-finance/custom-supertokens/=lib/custom-supertokens/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
